'use client'

import { useMemo, useState } from 'react'
import * as XLSX from 'xlsx'
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, PieChart, Pie, Cell } from 'recharts'
import { Upload, RefreshCcw, Search, FileSpreadsheet, AlertTriangle, CheckCircle2 } from 'lucide-react'

const ECI_HEADERS=['State Id','State Name','District Number','District Name','AC Number','Asmbly Name','POLLING STATION','Notice Generated','Pending for Notice Generation','Notice Delivered','Notice Pending Delivery','Hearings Held','Hearing Date Lapsed','Reschedule Date Lapsed','DEO-Status Total Pending','DEO-Status Pending GT 5 Days','DEO-Status Verified','DEO-Status Not Verified','ERO/AERO Status Found Ineligible For Final w.r.t. Notice Generated','ERO/AERO Status Parked For Final Publication','ERO/AERO Parked For Final Publication w.r.t. Others']
type Row=Record<string,any>; type Model={eci:Row[];ps:Row[];schedule:Row[];dates:string[];source:string;uploadedAt:string}
const fmt=(n:number)=>new Intl.NumberFormat('en-IN').format(Number(n||0)); const safe=(v:unknown)=>v==null?'':String(v)
const keyOf=(v:unknown)=>{if(v instanceof Date&&!isNaN(v.getTime()))return v.toISOString().slice(0,10);const d=new Date(safe(v));return isNaN(d.getTime())?'':d.toISOString().slice(0,10)}
const labelOf=(k:string)=>k?new Intl.DateTimeFormat('en-IN',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(k+'T00:00:00')):'—'; const num=(v:unknown)=>{const n=Number(v);return Number.isFinite(n)?n:0}
function read(wb:XLSX.WorkBook,name:string){const s=wb.Sheets[name];return s?XLSX.utils.sheet_to_json<Row>(s,{defval:null,raw:true}):[]}
function build(wb:XLSX.WorkBook,source:string):Model{
 const eci=read(wb,'ECI_INPUT').filter(r=>num(r['AC Number'])===34||safe(r['Asmbly Name']).trim().toUpperCase()==='MATIALA')
 const ps=read(wb,'PS_MASTER').filter(r=>num(r['PS No.'])>0), schedule=read(wb,'HEARING_DATA').filter(r=>num(r['PS No.'])>0).map(r=>({...r,dateKey:keyOf(r.Date)})), dates=[...new Set(schedule.map(r=>r.dateKey).filter(Boolean))].sort()
 return {eci,ps,schedule,dates,source,uploadedAt:new Date().toLocaleString('en-IN')}
}
export default function Home(){
 const [model,setModel]=useState<Model|null>(null),[selectedDate,setSelectedDate]=useState(''),[query,setQuery]=useState(''),[tab,setTab]=useState<'overview'|'officers'|'ps'|'eci'>('overview'),[error,setError]=useState('')
 const load=async(f:File)=>{try{setError('');const wb=XLSX.read(await f.arrayBuffer(),{type:'array',cellDates:true});for(const s of ['ECI_INPUT','PS_MASTER','HEARING_DATA'])if(!wb.Sheets[s])throw new Error(`${s} sheet not found. Please upload the same dashboard workbook structure you use for the ECI paste/update workflow.`);const m=build(wb,f.name);if(!m.eci.length)throw new Error('No AC-34 / MATIALA rows were found in ECI_INPUT.');setModel(m);setSelectedDate(m.dates[m.dates.length-1]||'')}catch(e){setError(e instanceof Error?e.message:'Unable to read workbook.')}}
 const active=useMemo(()=>model?.schedule.filter(r=>r.dateKey===selectedDate)||[],[model,selectedDate]), psMap=useMemo(()=>new Map((model?.ps||[]).map(p=>[num(p['PS No.']),p])),[model]), enriched=useMemo(()=>active.map(r=>({...r,...(psMap.get(num(r['PS No.']))||{})})),[active,psMap])
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return enriched.filter(r=>!q||[r.Officer,r['Hearing Centre'],r.BLO,r.Supervisor,r['PS No.'],r['Old PS No.'],r.Locality,r['Polling Area']].some(v=>safe(v).toLowerCase().includes(q)))},[enriched,query])
 const officerSummary=useMemo(()=>{const m=new Map<string,Row>();for(const r of enriched){const k=`${safe(r.Officer)}|||${safe(r['Hearing Centre'])}`,x=m.get(k)||{Officer:r.Officer,'Officer Mobile':r['Officer Mobile'],'Hearing Centre':r['Hearing Centre'],PS:0,Scheduled:0,Generated:0,Delivered:0,Pending:0,Held:0};x.PS++;x.Scheduled+=num(r['Scheduled Notices for Hearing']);x.Generated+=num(r['Notice Generated']);x.Delivered+=num(r['Notice Delivered']);x.Pending+=num(r['Notice Pending Delivery']);x.Held+=num(r['Hearings Held']);m.set(k,x)}return [...m.values()]},[enriched])
 const total=useMemo(()=>enriched.reduce((a,r)=>({ps:a.ps+1,scheduled:a.scheduled+num(r['Scheduled Notices for Hearing']),generated:a.generated+num(r['Notice Generated']),delivered:a.delivered+num(r['Notice Delivered']),pending:a.pending+num(r['Notice Pending Delivery']),held:a.held+num(r['Hearings Held'])}),{ps:0,scheduled:0,generated:0,delivered:0,pending:0,held:0}),[enriched])
 const global=useMemo(()=>model?.eci.reduce((a,r)=>({generated:a.generated+num(r['Notice Generated']),delivered:a.delivered+num(r['Notice Delivered']),pending:a.pending+num(r['Notice Pending Delivery']),held:a.held+num(r['Hearings Held']),lapsed:a.lapsed+num(r['Hearing Date Lapsed'])+num(r['Reschedule Date Lapsed']),verified:a.verified+num(r['DEO-Status Verified']),notVerified:a.notVerified+num(r['DEO-Status Not Verified'])}),{generated:0,delivered:0,pending:0,held:0,lapsed:0,verified:0,notVerified:0}),null),[model]); const pct=total.scheduled?Math.round(total.delivered/total.scheduled*100):0
 const chart=officerSummary.map(o=>({name:safe(o.Officer).replace(/^SH\. |^SMT\. /,''),Scheduled:o.Scheduled,Delivered:o.Delivered,Pending:o.Pending}))
 return <div className="app-shell"><header className="topbar"><div className="brand"><div><div className="title">AC-34 MATIALA — SIR 2026 HEARING & NOTICE DASHBOARD</div><div className="subtitle">Upload the latest Excel and review the complete hearing position.</div></div>{model&&<div className="updated">Loaded: {model.uploadedAt}<br/>File: {model.source}</div>}</div></header><main className="page">
 <div className="toolbar"><div className="field"><label>ECI Input Workbook</label><label className="upload"><Upload size={16}/> Upload latest Excel<input type="file" accept=".xlsx,.xls" onChange={e=>e.target.files?.[0]&&load(e.target.files[0])}/></label></div><div className="field"><label>Hearing Date</label><select disabled={!model} value={selectedDate} onChange={e=>setSelectedDate(e.target.value)}><option value="">Select hearing date</option>{model?.dates.map(d=><option key={d} value={d}>{labelOf(d)}</option>)}</select></div><div className="field"><label>Search</label><div style={{position:'relative'}}><Search size={16} style={{position:'absolute',left:11,top:12,color:'#829ab1'}}/><input className="upload" style={{paddingLeft:34,width:'100%'}} value={query} onChange={e=>setQuery(e.target.value)} placeholder="PS / officer / centre / BLO..."/></div></div><button className="tab" onClick={()=>model&&setSelectedDate(model.dates[model.dates.length-1]||'')}><RefreshCcw size={14}/> Latest date</button><div className="status">{model?`${fmt(model.eci.length)} ECI rows • ${fmt(model.ps.length)} PS master rows • ${model.dates.length} hearing dates`:'Upload the ECI workbook to begin'}</div></div>
 {error&&<div className="error"><AlertTriangle size={15} style={{verticalAlign:'-3px',marginRight:6}}/>{error}</div>}
 {!model?<div className="panel" style={{marginTop:16}}><div className="empty"><FileSpreadsheet size={42}/><h2>Upload your latest ECI dashboard workbook</h2><p>Use the same workbook you already update after pasting the ECI report. The application reads <b>ECI_INPUT</b>, <b>PS_MASTER</b>, and <b>HEARING_DATA</b> and keeps the source workbook out of GitHub.</p></div></div>:<>
 <div className="section-title">Selected Hearing Date — {labelOf(selectedDate)}</div><div className="cards"><div className="card"><div className="kicker">Polling Stations</div><div className="metric">{fmt(total.ps)}</div><div className="delta">scheduled</div></div><div className="card"><div className="kicker">Scheduled Notices</div><div className="metric">{fmt(total.scheduled)}</div><div className="delta">hearing workload</div></div><div className="card"><div className="kicker">Notice Generated</div><div className="metric">{fmt(total.generated)}</div><div className="delta">selected date</div></div><div className="card"><div className="kicker">Delivered</div><div className="metric">{fmt(total.delivered)}</div><div className="delta">{pct}% of scheduled</div></div><div className="card"><div className="kicker">Pending Delivery</div><div className="metric">{fmt(total.pending)}</div><div className="delta">remaining</div></div><div className="card"><div className="kicker">Hearings Held</div><div className="metric">{fmt(total.held)}</div><div className="delta">recorded</div></div></div>
 {total.ps===0&&<div className="error" style={{marginTop:12}}>No hearing is scheduled for the selected date.</div>}
 <div className="tabs"><button className={`tab ${tab==='overview'?'active':''}`} onClick={()=>setTab('overview')}>Overview</button><button className={`tab ${tab==='officers'?'active':''}`} onClick={()=>setTab('officers')}>Officer-wise</button><button className={`tab ${tab==='ps'?'active':''}`} onClick={()=>setTab('ps')}>PS-wise Detail</button><button className={`tab ${tab==='eci'?'active':''}`} onClick={()=>setTab('eci')}>ECI Status</button></div>
 {tab==='overview'&&<><div className="grid2"><div className="panel"><h3>Officer workload for selected date</h3><div className="chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={chart} margin={{top:8,right:15,left:-20,bottom:30}}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name" angle={-25} textAnchor="end" interval={0} height={60} fontSize={10}/><YAxis fontSize={10}/><Tooltip/><Bar dataKey="Scheduled" fill="#315a7d"/><Bar dataKey="Delivered" fill="#2f855a"/><Bar dataKey="Pending" fill="#c0841a"/></BarChart></ResponsiveContainer></div></div><div className="panel"><h3>Notice delivery status</h3><div className="chart"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={[{name:'Delivered',value:total.delivered},{name:'Pending',value:total.pending}]} cx="50%" cy="50%" innerRadius={62} outerRadius={92} dataKey="value" label><Cell fill="#2f855a"/><Cell fill="#c0841a"/></Pie><Tooltip/></PieChart></ResponsiveContainer></div><div className="small" style={{textAlign:'center'}}>{fmt(total.delivered)} delivered • {fmt(total.pending)} pending</div></div></div><div className="panel" style={{marginTop:14}}><h3>Operational snapshot from latest ECI data</h3><div className="details"><div className="detail"><b>Total notice generated</b>{fmt(global?.generated||0)}</div><div className="detail"><b>Total notice delivered</b>{fmt(global?.delivered||0)}</div><div className="detail"><b>Total pending delivery</b>{fmt(global?.pending||0)}</div><div className="detail"><b>Hearing + reschedule lapses</b>{fmt(global?.lapsed||0)}</div><div className="detail"><b>DEO verified</b>{fmt(global?.verified||0)}</div><div className="detail"><b>DEO not verified</b>{fmt(global?.notVerified||0)}</div><div className="detail"><b>PS master records</b>{fmt(model.ps.length)}</div><div className="detail"><b>Hearing dates</b>{fmt(model.dates.length)}</div></div></div></>}
 {tab==='officers'&&<div className="panel"><h3>Officer-wise Hearing Summary</h3><div className="table-wrap"><table className="table"><thead><tr><th>Officer</th><th>Mobile</th><th>Hearing Centre</th><th>PS</th><th>Scheduled</th><th>Generated</th><th>Delivered</th><th>Pending</th><th>Held</th><th>Delivery %</th></tr></thead><tbody>{officerSummary.map((o,i)=><tr key={i}><td><b>{safe(o.Officer)}</b></td><td>{safe(o['Officer Mobile'])}</td><td>{safe(o['Hearing Centre'])}</td><td>{fmt(o.PS)}</td><td className="right">{fmt(o.Scheduled)}</td><td className="right">{fmt(o.Generated)}</td><td className="right">{fmt(o.Delivered)}</td><td className="right">{fmt(o.Pending)}</td><td className="right">{fmt(o.Held)}</td><td><span className={`badge ${o.Scheduled&&o.Delivered/o.Scheduled>.8?'good':o.Scheduled&&o.Delivered/o.Scheduled>.4?'warn':'danger'}`}>{o.Scheduled?Math.round(o.Delivered/o.Scheduled*100)+'%':'—'}</span></td></tr>)}<tr><td><b>TOTAL</b></td><td colSpan={2}></td><td>{fmt(total.ps)}</td><td className="right"><b>{fmt(total.scheduled)}</b></td><td className="right"><b>{fmt(total.generated)}</b></td><td className="right"><b>{fmt(total.delivered)}</b></td><td className="right"><b>{fmt(total.pending)}</b></td><td className="right"><b>{fmt(total.held)}</b></td><td><b>{pct}%</b></td></tr></tbody></table></div></div>}
 {tab==='ps'&&<div className="panel"><h3>PS-wise Details — {labelOf(selectedDate)}</h3><div className="small" style={{marginBottom:10}}>{filtered.length} records</div><div className="table-wrap"><table className="table"><thead><tr><th>Officer</th><th>Centre</th><th>PS No.</th><th>Old PS</th><th>BLO</th><th>Supervisor</th><th>Scheduled</th><th>Generated</th><th>Delivered</th><th>Pending</th><th>Held</th><th>Locality / Polling Area</th></tr></thead><tbody>{filtered.map((r,i)=><tr key={i}><td>{safe(r.Officer)}</td><td>{safe(r['Hearing Centre'])}</td><td><b>{safe(r['PS No.'])}</b></td><td>{safe(r['Old PS No.'])}</td><td>{safe(r.BLO)}<br/><span className="small">{safe(r['BLO Mobile'])}</span></td><td>{safe(r.Supervisor)}<br/><span className="small">{safe(r['Supervisor Mobile'])}</span></td><td className="right">{fmt(num(r['Scheduled Notices for Hearing']))}</td><td className="right">{fmt(num(r['Notice Generated']))}</td><td className="right">{fmt(num(r['Notice Delivered']))}</td><td className="right">{fmt(num(r['Notice Pending Delivery']))}</td><td className="right">{fmt(num(r['Hearings Held']))}</td><td>{safe(r.Locality)}<br/><span className="small">{safe(r['Polling Area'])}</span></td></tr>)}{!filtered.length&&<tr><td colSpan={12}><div className="empty">No matching PS records.</div></td></tr>}</tbody></table></div></div>}
 {tab==='eci'&&<div className="panel"><h3>ECI Status — Complete AC-34 Input</h3><div className="small" style={{marginBottom:10}}>Raw ECI rows for audit and reconciliation.</div><div className="table-wrap"><table className="table"><thead><tr>{ECI_HEADERS.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{model.eci.map((r,i)=><tr key={i}>{ECI_HEADERS.map(h=><td key={h}>{safe(r[h])}</td>)}</tr>)}</tbody></table></div></div>}
 <div className="footer-note"><CheckCircle2 size={13} style={{verticalAlign:'-2px',marginRight:5}}/>Workbook data is processed in the browser and is not uploaded to GitHub by the dashboard.</div></>}</main></div>
}
