'use client'

import { useEffect, useMemo, useState } from 'react'
import * as XLSX from 'xlsx'
import { Upload, RefreshCcw, Search, FileSpreadsheet, AlertTriangle, Settings2 } from 'lucide-react'
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, PieChart, Pie, Cell } from 'recharts'

type Row = Record<string, any>
type Master = { ps: Row[]; schedule: Row[] }
const fmt=(v:any)=>new Intl.NumberFormat('en-IN').format(Number(v||0))
const safe=(v:any)=>v==null?'':String(v)
const n=(v:any)=>Number(v||0)
const key=(v:any)=>{if(v instanceof Date&&!isNaN(v.getTime()))return v.toISOString().slice(0,10);const d=new Date(safe(v));return isNaN(d.getTime())?'':d.toISOString().slice(0,10)}
const label=(d:string)=>d?new Intl.DateTimeFormat('en-IN',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(d+'T00:00:00')):'—'
const read=(wb:XLSX.WorkBook,name:string)=>wb.Sheets[name]?XLSX.utils.sheet_to_json<Row>(wb.Sheets[name],{defval:null,raw:true}):[]

function extractEci(wb:XLSX.WorkBook){
  const names=wb.SheetNames
  let rows=read(wb,'sirNoticeGenerate')
  if(!rows.length) rows=read(wb,'ECI_INPUT')
  if(!rows.length){ for(const s of names){const r=read(wb,s);if(r[0]&&('Part No' in r[0]||'POLLING STATION' in r[0])){rows=r;break}} }
  return rows.filter(r=>n(r['AC Number'])===34||safe(r['Asmbly Name']).toUpperCase()==='MATIALA')
}

function extractMaster(wb:XLSX.WorkBook):Master{
  const ps=read(wb,'PS_MASTER')
  const h=read(wb,'HEARING_DATA')
  return {ps, schedule:h.filter(r=>n(r['PS No.'])>0).map(r=>({dateKey:key(r.Date),ps:n(r['PS No.']),scheduled:n(r['Scheduled Notices for Hearing'])}))}
}

export default function Home(){
 const [eci,setEci]=useState<Row[]>([]),[master,setMaster]=useState<Master|null>(null),[date,setDate]=useState(''),[q,setQ]=useState(''),[tab,setTab]=useState<'overview'|'officers'|'ps'|'eci'>('overview'),[error,setError]=useState(''),[source,setSource]=useState(''),[ready,setReady]=useState(false)
 useEffect(()=>{try{const raw=localStorage.getItem('ac34_master');if(raw)setMaster(JSON.parse(raw))}catch{}setReady(true)},[])
 const saveMaster=(m:Master)=>{setMaster(m);localStorage.setItem('ac34_master',JSON.stringify(m));setDate(m.schedule.map(x=>x.dateKey).filter(Boolean).sort().at(-1)||'')}
 const uploadDashboard=async(f:File)=>{try{setError('');const wb=XLSX.read(await f.arrayBuffer(),{type:'array',cellDates:true});const m=extractMaster(wb);if(!m.ps.length||!m.schedule.length)throw new Error('Dashboard workbook must contain PS_MASTER and HEARING_DATA sheets.');saveMaster(m);setSource(f.name+' (one-time master setup)')}catch(e){setError(e instanceof Error?e.message:'Unable to read dashboard workbook.')}}
 const uploadEci=async(f:File)=>{try{setError('');const wb=XLSX.read(await f.arrayBuffer(),{type:'array',cellDates:true});const rows=extractEci(wb);if(!rows.length)throw new Error('No AC-34 / MATIALA rows found. This does not look like the ECI NOTICE_REPORT_PART_WISE file.');setEci(rows);setSource(f.name);if(master)setDate(master.schedule.map(x=>x.dateKey).filter(Boolean).sort().at(-1)||'')}catch(e){setError(e instanceof Error?e.message:'Unable to read ECI file.')}}
 const dates=useMemo(()=>[...new Set((master?.schedule||[]).map(x=>x.dateKey).filter(Boolean))].sort(),[master])
 const eciMap=useMemo(()=>new Map(eci.map(r=>[n(r['Part No']??r['POLLING STATION']),r])),[eci])
 const psMap=useMemo(()=>new Map((master?.ps||[]).map(r=>[n(r['PS No.']),r])),[master])
 const active=useMemo(()=> (master?.schedule||[]).filter(r=>r.dateKey===date).map(s=>{const p=psMap.get(s.ps)||{};const e=eciMap.get(s.ps)||{};return {...p,...e,'PS No.':s.ps,'Scheduled Notices for Hearing':s.scheduled,'Notice Pending Delivery':s.scheduled-n(e['Notice Delivered']),'Date':s.dateKey}}),[master,date,eciMap,psMap])
 const filtered=useMemo(()=>{const x=q.trim().toLowerCase();return active.filter(r=>!x||[r['PS No.'],r['Old PS No.'],r.Officer,r['Hearing Centre'],r.BLO,r.Supervisor,r.Locality,r['Polling Area']].some(v=>safe(v).toLowerCase().includes(x)))},[active,q])
 const total=useMemo(()=>active.reduce((a,r)=>({ps:a.ps+1,scheduled:a.scheduled+n(r['Scheduled Notices for Hearing']),generated:a.generated+n(r['Notice Generated']),delivered:a.delivered+n(r['Notice Delivered']),pending:a.pending+n(r['Notice Pending Delivery']),held:a.held+n(r['Hearings Held'])}),{ps:0,scheduled:0,generated:0,delivered:0,pending:0,held:0}),[active])
 const officers=useMemo(()=>{const m=new Map<string,Row>();active.forEach(r=>{const k=`${safe(r.Officer)}|${safe(r['Hearing Centre'])}`,x=m.get(k)||{Officer:r.Officer,Mobile:r['Officer Mobile'],Centre:r['Hearing Centre'],PS:0,Scheduled:0,Generated:0,Delivered:0,Pending:0,Held:0};x.PS++;x.Scheduled+=n(r['Scheduled Notices for Hearing']);x.Generated+=n(r['Notice Generated']);x.Delivered+=n(r['Notice Delivered']);x.Pending+=n(r['Notice Pending Delivery']);x.Held+=n(r['Hearings Held']);m.set(k,x)});return [...m.values()]},[active])
 const global=useMemo(()=>eci.reduce((a,r)=>({generated:a.generated+n(r['Notice Generated']),delivered:a.delivered+n(r['Notice Delivered']),pending:a.pending+n(r['Notice Pending Delivery']),held:a.held+n(r['Hearings Held']),lapsed:a.lapsed+n(r['Hearing Date Lapsed'])+n(r['Reschedule Date Lapsed']),verified:a.verified+n(r['DEO-Status Verified']),notVerified:a.notVerified+n(r['DEO-Status Not Verified'])}),{generated:0,delivered:0,pending:0,held:0,lapsed:0,verified:0,notVerified:0}),[eci])
 const chart=officers.map(o=>({name:safe(o.Officer).replace(/^SH\. |^SMT\. /,''),Scheduled:o.Scheduled,Delivered:o.Delivered,Pending:o.Pending}))
 if(!ready)return null
 return <div className="app-shell"><header className="topbar"><div className="brand"><div><div className="title">AC-34 MATIALA — SIR 2026 HEARING & NOTICE DASHBOARD</div><div className="subtitle">Upload the latest ECI NOTICE_REPORT_PART_WISE file to refresh the live position.</div></div><div className="updated">{source&&<>Source: {source}<br/></>}{eci.length?`${fmt(eci.length)} ECI rows loaded`:master?`${fmt(master.ps.length)} PS master records saved`:''}</div></div></header><main className="page">
 <div className="toolbar">
  <div className="field"><label>Latest ECI Report — this is the file you normally upload</label><label className="upload"><Upload size={16}/> Upload ECI Excel<input type="file" accept=".xlsx,.xls" onChange={e=>e.target.files?.[0]&&uploadEci(e.target.files[0])}/></label></div>
  <div className="field"><label>Hearing Date</label><select disabled={!master} value={date} onChange={e=>setDate(e.target.value)}><option value="">Select hearing date</option>{dates.map(d=><option key={d} value={d}>{label(d)}</option>)}</select></div>
  <div className="field"><label>Search</label><div style={{position:'relative'}}><Search size={16} style={{position:'absolute',left:11,top:12,color:'#829ab1'}}/><input className="upload" style={{paddingLeft:34,width:'100%'}} value={q} onChange={e=>setQ(e.target.value)} placeholder="PS / officer / centre / BLO..."/></div></div>
  <button className="tab" onClick={()=>setDate(dates.at(-1)||'')}><RefreshCcw size={14}/> Latest date</button>
 </div>
 {!master&&<div className="panel setup"><Settings2 size={28}/><h2>One-time setup</h2><p>Upload your existing <b>AC34_Matiala_Hearing_Dashboard</b> workbook once. This saves the PS master and hearing schedule in this browser. After that, your normal workflow is only: <b>upload the ECI sheet</b>.</p><label className="upload"><Upload size={16}/> Upload dashboard workbook<input type="file" accept=".xlsx,.xls" onChange={e=>e.target.files?.[0]&&uploadDashboard(e.target.files[0])}/></label></div>}
 {error&&<div className="error"><AlertTriangle size={15}/> {error}</div>}
 {master&&eci.length>0&&<>
 <div className="section-title">Selected Hearing Date — {label(date)}</div><div className="cards"><div className="card"><div className="kicker">Polling Stations</div><div className="metric">{fmt(total.ps)}</div><div className="delta">scheduled</div></div><div className="card"><div className="kicker">Scheduled Notices</div><div className="metric">{fmt(total.scheduled)}</div><div className="delta">hearing workload</div></div><div className="card"><div className="kicker">Notice Generated</div><div className="metric">{fmt(total.generated)}</div></div><div className="card"><div className="kicker">Delivered</div><div className="metric">{fmt(total.delivered)}</div><div className="delta">{total.scheduled?Math.round(total.delivered/total.scheduled*100):0}% of scheduled</div></div><div className="card"><div className="kicker">Pending Delivery</div><div className="metric">{fmt(total.pending)}</div></div><div className="card"><div className="kicker">Hearings Held</div><div className="metric">{fmt(total.held)}</div></div></div>
 <div className="tabs"><button className={`tab ${tab==='overview'?'active':''}`} onClick={()=>setTab('overview')}>Overview</button><button className={`tab ${tab==='officers'?'active':''}`} onClick={()=>setTab('officers')}>Officer-wise</button><button className={`tab ${tab==='ps'?'active':''}`} onClick={()=>setTab('ps')}>PS-wise Detail</button><button className={`tab ${tab==='eci'?'active':''}`} onClick={()=>setTab('eci')}>ECI Status</button></div>
 {tab==='overview'&&<><div className="grid2"><div className="panel"><h3>Officer workload</h3><div className="chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={chart} margin={{top:8,right:15,left:-20,bottom:30}}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name" angle={-25} textAnchor="end" interval={0} height={60} fontSize={10}/><YAxis fontSize={10}/><Tooltip/><Bar dataKey="Scheduled"/><Bar dataKey="Delivered"/><Bar dataKey="Pending"/></BarChart></ResponsiveContainer></div></div><div className="panel"><h3>Notice delivery status</h3><div className="chart"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={[{name:'Delivered',value:total.delivered},{name:'Pending',value:total.pending}]} innerRadius={62} outerRadius={92} dataKey="value" label>{[0,1].map(i=><Cell key={i}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div></div></div><div className="panel" style={{marginTop:14}}><h3>Latest ECI operational snapshot</h3><div className="details"><div className="detail"><b>Notice generated</b>{fmt(global.generated)}</div><div className="detail"><b>Notice delivered</b>{fmt(global.delivered)}</div><div className="detail"><b>Pending delivery</b>{fmt(global.pending)}</div><div className="detail"><b>Hearing + reschedule lapses</b>{fmt(global.lapsed)}</div><div className="detail"><b>DEO verified</b>{fmt(global.verified)}</div><div className="detail"><b>DEO not verified</b>{fmt(global.notVerified)}</div></div></div></>}
 {tab==='officers'&&<div className="panel"><h3>Officer-wise Hearing Summary</h3><div className="table-wrap"><table className="table"><thead><tr><th>Officer</th><th>Mobile</th><th>Hearing Centre</th><th>PS</th><th>Scheduled</th><th>Generated</th><th>Delivered</th><th>Pending</th><th>Held</th><th>Delivery %</th></tr></thead><tbody>{officers.map((o,i)=><tr key={i}><td><b>{safe(o.Officer)}</b></td><td>{safe(o.Mobile)}</td><td>{safe(o.Centre)}</td><td>{o.PS}</td><td className="right">{fmt(o.Scheduled)}</td><td className="right">{fmt(o.Generated)}</td><td className="right">{fmt(o.Delivered)}</td><td className="right">{fmt(o.Pending)}</td><td className="right">{fmt(o.Held)}</td><td>{o.Scheduled?Math.round(o.Delivered/o.Scheduled*100)+'%':'—'}</td></tr>)}</tbody></table></div></div>}
 {tab==='ps'&&<div className="panel"><h3>PS-wise Detail — {fmt(filtered.length)} records</h3><div className="table-wrap"><table className="table"><thead><tr><th>PS</th><th>Old PS</th><th>Officer</th><th>Hearing Centre</th><th>BLO</th><th>Supervisor</th><th>Scheduled</th><th>Generated</th><th>Delivered</th><th>Pending</th><th>Held</th><th>Locality</th><th>Polling Area</th><th>Anomaly</th><th>Mapping</th><th>Grand Total</th><th>Voters</th></tr></thead><tbody>{filtered.map((r,i)=><tr key={i}><td><b>{safe(r['PS No.'])}</b></td><td>{safe(r['Old PS No.'])}</td><td>{safe(r.Officer)}</td><td>{safe(r['Hearing Centre'])}</td><td>{safe(r.BLO)}</td><td>{safe(r.Supervisor)}</td><td>{fmt(r['Scheduled Notices for Hearing'])}</td><td>{fmt(r['Notice Generated'])}</td><td>{fmt(r['Notice Delivered'])}</td><td>{fmt(r['Notice Pending Delivery'])}</td><td>{fmt(r['Hearings Held'])}</td><td>{safe(r.Locality)}</td><td>{safe(r['Polling Area'])}</td><td>{fmt(r['Total Anomaly/Discrepancy'])}</td><td>{fmt(r['Total No Mapping'])}</td><td>{fmt(r['Grand Total'])}</td><td>{fmt(r['Total Voters'])}</td></tr>)}</tbody></table></div></div>}
 {tab==='eci'&&<div className="panel"><h3>Raw ECI Status — {fmt(eci.length)} AC-34 rows</h3><div className="table-wrap"><table className="table"><thead><tr><th>Part No</th><th>Notice Generated</th><th>Pending Generation</th><th>Delivered</th><th>Pending Delivery</th><th>Hearings Held</th><th>Hearing Lapsed</th><th>Reschedule Lapsed</th><th>DEO Pending</th><th>DEO &gt;5 Days</th><th>Verified</th><th>Not Verified</th></tr></thead><tbody>{eci.map((r,i)=><tr key={i}><td><b>{safe(r['Part No']??r['POLLING STATION'])}</b></td><td>{fmt(r['Notice Generated'])}</td><td>{fmt(r['Pending for Notice Generation'])}</td><td>{fmt(r['Notice Delivered'])}</td><td>{fmt(r['Notice Pending Delivery'])}</td><td>{fmt(r['Hearings Held'])}</td><td>{fmt(r['Hearing Date Lapsed'])}</td><td>{fmt(r['Reschedule Date Lapsed'])}</td><td>{fmt(r['DEO-Status Total Pending'])}</td><td>{fmt(r['DEO-Status Pending GT 5 Days'])}</td><td>{fmt(r['DEO-Status Verified'])}</td><td>{fmt(r['DEO-Status Not Verified'])}</td></tr>)}</tbody></table></div></div>}
 </>}
 {master&&eci.length===0&&<div className="panel empty"><FileSpreadsheet size={40}/><h2>Upload the latest ECI report</h2><p>Your normal ECI file is the <b>NCT OF Delhi_NOTICE_REPORT_PART_WISE</b> export. Upload that file above; the dashboard will use it to refresh all ECI-derived numbers.</p></div>}
 </main></div>
}
